language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk8
  - oraclejdk11

env:
  - MILL_VERSION=0.3.6

script:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/${MILL_VERSION}/${MILL_VERSION} && chmod +x ~/bin/mill
  - mill -i version
  - mill -i it
  - mill -i jbake.publishLocal
