= JBake plugin for mill
:version: 0.1.0


Mill plugin to create static sites/blogs with JBake.

== Quickstart

[source,scala,subs="verbatim,attributes"]
----
// build.sc
import mill._
import $ivy.`de.tototec::de.tobiasroeser.mill.jbake:{version}`
import de.tobiasroeser.mill.jbake._

object site extends JBakeModule {

  def jbakeVersion = "2.6.4"

}
----

Generate the site:

[source,sh]
----
sh> mill site.jbake
----

Start a local Web-Server on Port 8820 with the generated site:

[source,sh]
----
sh> mill site.jbakeServe
----

== Configuration Options

To use the mill-jbake plugin, you have to extends link:jbake/src/de/tobiasroeser/mill/jbake/JBakeModule.scala[`de.tobiasroeser.mill.jbake.JBakeModule`].

You can override the following methods to customize the behaviour.

* `def jbakeVersion: T[String]` -
  The JBake version to be used. 
  Mandatory.
  Official release versions down to 2.2.0 are supported out of the box.
  If you need other version or local installation, you need also to customize `jbakeDistributionZip` or `jbakeDistributionDir`.

* `def sources: Sources` -
  The directory containing the JBake source files (`assets`, `content`, `templates`).
  Defaults to `src`.

* `def jbake: T[PathRef]` -
  Bake the site with JBake.

* `def jbakeServe(): Command[Unit]` -
  Starts a local Webserver to serve the content created with `jbake`.

* `def jbakeDistributionZip: T[PathRef]` -
  The JBake Binary Distribution ZIP archive.
  Defaults to downloading the distribution file from Bintray.

* `def jbakeDistributionDir: T[PathRef]` -
  The unpacked JBake Distribution.
  Defaults to the unpacked content of the `jbakeDistributionZip`.

* `def jbakeClasspath: T[Seq[PathRef]]` -
  The classpath used to run the JBake site generator.

* `def jbakeRun(args: String*): Command[Unit]` -
  Just calls the jbake tool with the given arguments.
  This might be helpful, if you need to run JBake with different options.

* `def jbakeProcessMode: ProcessMode` -
  Specify how the JBake tool should be executed.
  * `ClassLoader` runs JBake in s isolated classpath in the same JVM.
  * `SubProcess` spawns a new Java sub-process of each JBake tool invokation.
  Defaults to `ClassLoader` which is also faster.
  If you experience stability or memory issues, try to change this to `SubProcess`.

== Details


== Changelog

===

* Use a worker process to run JBake
* Added new ClassLoader based JBake worker, to speed up repetitive runs
* Added new `jbakeRun`target to just run the JBake tool with arbitrary arguments

=== mill-jbake 0.1.0 - 2019-02-17

* Initial public release
